version: '3.5'

services:

  ollama3:
    image: cro7/ollama3:0.0.1
    environment:
      OLLAMA_HOST: 0.0.0.0:8080
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
  ui:
    image: cro7/ollama3_ui:0.0.1
    environment:
      PORT: 8051
      UI_OLLAMA_HOST: ollama3:8080
    ports:
      - "80:8051"
    depends_on:
      - "ollama3"